name: React App Build and Upload to Blob Storage

on:
  push:
    branches:
      - develop

env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"

      - name: Install Packages
        working-directory: ./gym-tracker-website
        run: npm install

      - name: Build
        working-directory: ./gym-tracker-website
        run: npm run build --no-warnings

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --source $(System.DefaultWorkingDirectory)/build --destination \$web --connection-string {{ env.AZURE_STORAGE_CONNECTION_STRING }} --destination-path "/" --overwrite true
